language: 
        - java

os:
        - linux

addons:
  sonarcloud:
    organization: "dangeol-github"

sudo: true

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dangeol_ipi-java-350-ex
  

