language: java

jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: "dangeol-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  sonar:sonar -Dsonar.projectKey=dangeol_ipi-java-350-ex